### ISSUE TITLE
Login page UX upgrade

### ISSUE THREAD

**Issue by sak007** [sak007/SRIJAS#23]

**Comment by wizard-31** [comment]
Updated login page - 8f92ab0f0cc9777dd9bedc3a1ad341cbddd211b4
Please check.

Pending - To update Button. Will be creating a new Issue

**Comment by wizard-31** [comment]
Created Issue #33 for the same. Let me know if we're good to close this issue.

**Comment by sak007** [comment]
Tested and works fine
